name: MapleBrowser
options:
  bundleIdPrefix: net.teamceleste
  deploymentTarget:
    iOS: "13.0"
targets:
  MapleBrowser:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: MapleBrowser
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: net.teamceleste.maple
      PRODUCT_NAME: Maple Browser
      INFOPLIST_FILE: MapleBrowser/Info.plist
      SWIFT_VERSION: "5.0"
      IPHONEOS_DEPLOYMENT_TARGET: "13.0"
      TARGETED_DEVICE_FAMILY: "1,2"
    frameworks:
      - WebKit.framework
